name: CI/CD for Render Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.RENDER_API_KEY }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Echo SECRET key (masked)
        run: echo "API key is $API_KEY"

      - name: Install dependencies
        run: npm install

      - name: Trigger Backend Deploy
        run: curl -X POST ${{ secrets.RENDER_BACKEND_HOOK }}

      - name: Trigger Frontend Deploy
        run: curl -X POST ${{ secrets.RENDER_FRONTEND_HOOK }}
